# Site settings
title: Colin Rubbert
email: colinrubbert@gmail.com
description: > # This is a starter kit for Jekyll to build out Jekyll sites quicker.
baseurl: "/"

# Build settings
markdown: kramdown
permalink: pretty

host: 0.0.0.0
port: 3000

sass:
  sass_dir: assets/css
  style: :nested
