# Site settings
title: Jekyll Starter Kit
email: your-email@domain.com
description: > # This is a starter kit for Jekyll to build out Jekyll sites quicker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: colinrubbert
github_username:  colinrubbert

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
